[config]
default_to_workspace = false

[tasks.build-web-dbg]
# Use the `dev` flag and force optimization and debug assertions to skip `wasm-opt`, which strips debug info.
env = { "RUSTFLAGS" = "-Copt-level=3 -Cdebug-assertions -g" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "static", "--no-typescript", "--dev", "evanescence_web"]

[tasks.build-web]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "wasm", "--out-dir", "static", "--no-typescript", "evanescence_web"]
