[package]
name = "evanescence_core"
version = "0.2.0"
authors = ["al2me6 <alvin.q.meng@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4"
getrandom = { version = "*", features = ["js"] }# Transitive dependency of nanorand.
getset = "0.1"
indoc = "1"
nanorand = { version = "0.5", default-features = false, features = ["wyrand", "std", "getrandom"] }
num-complex = "0.3"
strum = { version = "0.20", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"
lazy_static = "1"

[[bench]]
name = "benchmarks"
harness = false
