[package]
name = "evanescence_core"
version = "0.1.0"
authors = ["al2me6 <alvin.q.meng@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4"
getrandom = "0.2"
getset = "0.1"
indoc = "1"
num-complex = "0.3"
oorandom = "11"
strum = { version = "0.20", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"
lazy_static = "1"

[[bench]]
name = "benchmarks"
harness = false
