[package]
name = "evanescence_core"
description = "Library for computing and working with hydrogenic wavefunctions."
version = "0.4.0"
authors = ["al2me6 <alvin.q.meng@gmail.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/al2me6/evanescence"
edition = "2018"

[dependencies]
approx = "0.4"
getset = "0.1"
indoc = "1"
nanorand = { version = "0.5", default-features = false, features = ["wyrand", "std", "getrandom"] }
num-complex = "0.4"
serde = { version = "1", features = ["derive"], optional = true, default-features = false }
strum = { version = "0.20", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
criterion = "0.3"
lazy_static = "1"

[[bench]]
name = "benchmarks"
harness = false
