[package]
name = "evanescence_web"
version = "0.3.6"
authors = ["al2me6 <alvin.q.meng@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1"
derivative = "2"
evanescence_core = { path = "../evanescence_core" }
log = "0.4"
once_cell = "1"
pkg-version = "1"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.1"
strum = "0.20"
wasm-bindgen = { version = "0.2" }
wasm-logger = "0.2"
web-sys = { version = "0.3", features = [
    "CssStyleDeclaration",
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlSpanElement",
    "Node",
    "Window",
] }
yew = "0.17"
yewtil = "0.3"
yew-state = "0.4"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ["-g", "-O3"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4"]
