name: Run benchmarks
on:
  push:
    branches:
      - dev

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            override: true
      - name: Run benchmarks
        run: cd evanescence_core && cargo bench --bench benchmarks -- --noplot --output-format bencher | tee output.txt
      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: evanescence_core/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
