name: Deploy website
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          rustup toolchain update nightly
          rustup default nightly
          cargo install wasm-bindgen-cli
      - name: Compile
        run: |
          cd evanescence_web
          wasm-pack build --target web --out-name wasm --out-dir ./static
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          path: evanescence_web/static
      - name: Switch to gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: Push to gh-pages
        run: git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy website at commit $(git rev-parse HEAD)"
          git push
