name: Deploy website
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            target: wasm32-unknown-unknown
            profile: minimal
            override: true

      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Compile
        run: |
          cd evanescence_web
          trunk build --release

      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            evanescence_web/dist

      - name: Switch to gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Push to gh-pages
        run: |
          ls -la
          if git diff-index --quiet HEAD --; then
            echo "No changes detected!"
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git status
            git fetch origin
            git commit -m "Deploy website at commit $(git rev-parse origin/master)"
            git push
          fi
